service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  randomNumberGenerator:
    handler: src/handler.generateRandomNumber
    timeout: 10 # in seconds
    memorySize: 128 # in MB
